### ISSUE TITLE
Implement rail_linetalk

### ISSUE THREAD

**Issue by cratuki** [solent-eng/solent#144]
Like line-console, but supporting multiple users and requiring login.

Name, rail_linetalk

Do the scenario for it. This can lead into a MUD tutorial.

SSL would be ideal, but we may want to hold off in this round. Expect this to be awkward for multi-platform.

Abolish the existing line-console. It is an open console, which encourages bad habits.

**Comment by cratuki** [comment]
I had a look into SSL, and it might be less work than I expected.

SSL can be annoying in that it requires certificate generation. So it might be easy to implement the functionality, but annoying to use in practice.

Still, it is worth a look. A well-secured linetalk system could become a defactor standard approach to building connections between systems.

**Comment by cratuki** [comment]
Have pushed branch 144. This has a basic rail_linetalk in it, and a demonstration app. No ssl yet.

**Comment by Evanerfbdgcn** [comment]
Is there any specific graphics engine you had in mind that would be SSL compatable? Or is it easier for it to be text based for now

**Comment by cratuki** [comment]
Graphics engine is a different issue. And - less fundamental. (I'm going to continue this conversation away from the thread.)

**Comment by cratuki** [comment]
** Ended up putting some bugfixes in to the solent.demo packages, and surrounding tweaks. This was not deliberate, it was a side-effect of me having incomplete branch 144 issues still open.

**Comment by cratuki** [comment]
Committed. Did not end up going deep on SSL in this issue.
